### ISSUE TITLE
ACSI support

### ISSUE THREAD

**Issue by TzOk83** [harbaum/MiSTeryNano#19]
I have tried 4 different hard disk images with the same result: 4 bombs.

Images I've tried:
http://www.mediafire.com/file/f1yq3z38741vwgx/SatanDisk2Gb_v1.rar
https://kerlinux.org/public/Atari_ST_Games_Petari_20181212_ACSI_1_6GB_5+4x400MB_ICD.zip
and 2 blank images from STEEM 4 (MEGAFILE 60, SH204).

I've renamed them from .img to .hd, all are raw binary images with some HDD driver installed.

**Comment by harbaum** [comment]
Does AHDI or Hddriver or anything else loaded from floppy disk see a harddisk?

**Comment by harbaum** [comment]
Ah ... do you use TOS 2.06? I see something like that with that version as well. Please try TOS 1.62 or TOS 1.04

**Comment by harbaum** [comment]
The TOS 2.06 ACSI boot issue is now fixed and will be part of the next release

**Comment by harbaum** [comment]
> Yes, I was using STE & TOS 2.06, with ST & TOS 1.4 it works, but I also tried PPhdrv 1.01hs and it works extremely slow; opening a folder in GEM takes well over 15 sec.
> 
> The RetroWiki image gives me 2 bombs at boot.

What is pphdrv 1.01hs ? And what is "the retrowiki image" ?

**Comment by TzOk83** [comment]
pphdrv 1.01hs is Peter Putnik HDD Driver v1.01HS (2014), and RetroWiki Image is one of the images I gave link to in the first post (SatanDisk2Gb_v1.rar).

**Comment by harbaum** [comment]
It's difficult to debug Peters stuff as it's closed source and not documented. Someone would need to disassemble e.g. the boot sector of that image and try to figure out what that does different than all other drivers.

**Comment by harbaum** [comment]
The ppera driver relies on a hardware flaw in the DMA in the handling of the A1 signal. I traced the IO access of the ppera driver in Hatari, replayed this in my simulation of the ACSI chip, had the same broken behaviour. Now seeing the issue I knew where to look in hatari to see how they deal with this and found this comment:

https://github.com/hatari/hatari/blob/97eddba41d12661b0218850c160949e8510a6caa/src/hdc.c#L1139-L1141

**Comment by harbaum** [comment]
Fixed in release 1.2.4 ... please give it a try

**Comment by TzOk83** [comment]
Thank you for this release. The old PPDRV 0.98 (2009) works ok now, but the slightly newer version 1.01 (2014) still crashes (no disk access at all in GEM or sees a disk but with 0 bytes in size). Please take a look at the enclosed disk image.
[PP60.zip](https://github.com/harbaum/MiSTeryNano/files/14143878/PP60.zip)

On the bright side, I see a major improvement in USB mice/keyboard compatibility (yet, my gamepad still doesn't work). The mouse pointer is now much more responsive (less laggy), but fast movements make Atari lose the "track" of mouse pulses.

**Comment by harbaum** [comment]
I'll have a look at that version. But the old version was already pretty broken ...

**Comment by harbaum** [comment]
What gamepad are you trying to use?

**Comment by TzOk83** [comment]
PiHut SNES: https://thepihut.com/products/raspberry-pi-compatible-usb-gamepad-controller-snes-style

**Comment by harbaum** [comment]
> PiHut SNES: https://thepihut.com/products/raspberry-pi-compatible-usb-gamepad-controller-snes-style

I have a very similar cheap one. Will give it a try. You can of course always donate one and I'll see what I can do.

**Comment by harbaum** [comment]
I think I found the issue the the later ppera driver. Since I didn't want to do a full release for this small change I just updated the existing release 1.2.4

So please re-download 1.2.4 and give it a try,

**Comment by Unixware** [comment]
Just my 2p here: PPhdrv is bit buggy... I had issues with that even on my past MiST ...  ICD pro works fine with MiSTeryNano plus is way faster
